name: CI

on: [push]

jobs:
  build-test-fuzz:
    name: Build, Test and Fuzz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri

      - name: Cache Cargo registry and build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Build
        run: cargo build --verbose

      - name: Test
        env:
          RUSTFLAGS: "-Z sanitizer=address"
        run: cargo test --target x86_64-unknown-linux-gnu --verbose

      - name: Test with Miri
        run: cargo miri test --verbose

      - name: Test with Realloc
        env:
          RUSTFLAGS: "-Z sanitizer=address"
        run: cargo test --features realloc --target x86_64-unknown-linux-gnu --verbose

      - name: Test with Realloc with Miri
        run: cargo miri test --features realloc --verbose

      - name: Build Fuzz Docker Image
        run: docker build -t lite-alloc-fuzz .

      - name: Run Fuzz Tests (Docker)
        # This will run the default CMD defined in Dockerfile:
        # bash -c "cargo fuzz run freelist ... && cargo fuzz run bump_freelist ... && ..."
        run: docker run --rm lite-alloc-fuzz
